### ISSUE TITLE
文件无法下载，怎么处理？

### ISSUE THREAD

**Issue by BluerAngala** [mikoshu/gewechaty#1]
感谢作者，近期有业务需要用到很感谢封装！

我注意到 gewe 的API只有下载图片，没有下载文件。

在某些业务场景中，可能需要获取文件的内容，这个怎么处理？

**Comment by mikoshu** [comment]
目前作者gewe镜像不支持下载文件功能 后续如果有支持我会同步更新 目前免费版的都没办法下载，如果需要下载图片可以看看付费版本的 cdn下载功能 http://doc.geweapi.com/api-139908333

**Comment by BluerAngala** [comment]
好的，谢谢啦。
