### ISSUE TITLE
接收图片/文件消息失败

### ISSUE THREAD

**Issue by imlinhanchao** [mikoshu/gewechaty#16]
收到图片消息后执行：
```js
if (msg.type() === bot.Message.Type.Image) {
  const filebox = await msg.toFileBox();
  const filePath = path.join(imgStatic, filebox.name);
  filebox.toFile(filePath);
}
```
确认保存的图片，内容非图片，而是文本 `{"ret":401,"msg":"请求访问：xxxxxxx，认证失败，无法访问系统资源"}`

收到文件消息后执行：
```js
if (msg.type() === bot.Message.Type.File) {
    const filebox = await msg.toFileBox();
    const filePath = path.join(fileStatic, filebox.name); // 执行到此处确认 filebox为 null，报错：Uncaught TypeError TypeError: Cannot read properties of null (reading 'name')
    filebox.toFile(filePath);
    wss.send({ type: bot.Message.Type.File, data: fileUrl });
  }
```

请教一下，是否我理解有误，错误调用接收函数？

**Comment by mikoshu** [comment]
{"ret":401,"msg":"请求访问：xxxxxxx，认证失败，无法访问系统资源"} 这个是docker里的报错 你看看你file_api 设置的有没有问题

**Comment by imlinhanchao** [comment]
和readme设置是一致的，有没有什么办法可以验证？

**Comment by mikoshu** [comment]
直接放问 ip:2532 看看会不会返回nginx的404

**Comment by imlinhanchao** [comment]
是返回 404，刚刚发现file_api确实配错了，没注意到端口不同 😂。试了一下图片可以了，文件仍然是 null。

**Comment by mikoshu** [comment]
因为这个gewechat项目本身不支持文件下载 只能是图片

**Comment by imlinhanchao** [comment]
哦哦~好的。谢谢~

**Comment by mikoshu** [comment]
别挣扎了 上游的docker不支持图片以外的内容下载

**Comment by alanhe421** [comment]
> 别挣扎了 上游的docker不支持图片以外的内容下载

那个限制问题，我知道了，看了下上游API文档，下载只有图片支持。

这里下载图片我也没成功。我看我打印出来的filebox.name是download.我理解应该是个文件名吧，

<img width="954" alt="Image" src="https://github.com/user-attachments/assets/489e715a-bb41-4182-98a1-3a3cbaa32cbb" />

<img width="773" alt="Image" src="https://github.com/user-attachments/assets/41050fdb-c891-4b32-907b-d71bc905d751" />
