### ISSUE TITLE
关于微信接受图片文件 解析内容

### ISSUE THREAD

**Issue by xiamo008** [mikoshu/gewechaty#18]
大佬，你好，我想用本项目登陆机器人后，接收图片，图片中包含了我需要的信息，比如图片11位数字信息等等
我现在有个难点就是，机器人一直无法解析图片，因为通讯是加密了的，我现在不知道怎么弄，才能把微信接收到的图片，正常保存下来，或者直接解析，我试过ocr的插件，单纯的在本地上解析图片没有问题。我是在linux上跑的机器人。
求教大佬给个思路。

**Comment by mikoshu** [comment]
下载图片到本地再解析
const filebox = await msg.toFileBox();
  // 传入一个文件路径 推荐为静态托管目录 如：`${process.cwd()}/static/download` 这样后续需要发送图片时可以直接使用静态托管的http路径
  const fileurl = path.join(staticUrl, filebox.name);
  filebox.toFile(fileurl);

**Comment by xiamo008** [comment]
好的，谢谢大佬。非常感谢

**Comment by alanhe421** [comment]
怎么发图片呢，我这里测试没效果

room.say(Filebox.fromFile(path.join(__dirname, `temp/Snipaste_2025-01-15_16-23-32.jpg`), fromContact))

**Comment by alanhe421** [comment]
咨询下

await room.say(Filebox.fromFile(path.join(__dirname, `temp/Snipaste_2025-01-15_16-23-32.jpg`)), fromContact);


发送图片呢，我测试上述代码不work

**Comment by mikoshu** [comment]
你就这么一句没上下文咋看

**Comment by alanhe421** [comment]
> 你就这么一句没上下文咋看

我意思是不是这么玩的，这里也确实没什么上下文，因为我测试了下，这里发送没work，但没看到报错。


```js
  const room = await msg.room();
  const fromContact = await msg.from();
```

**Comment by mikoshu** [comment]
有个问题 发送图片时候不支持@  用户 微信也没这个功能 只有文字内容可以

**Comment by alanhe421** [comment]
> 有个问题 发送图片时候不支持@ 用户 微信也没这个功能 只有文字内容可以

偶偶，谢谢，试了下是有这点。
