### ISSUE TITLE
docker 详细信息

### ISSUE THREAD

**Issue by softguy888** [mikoshu/gewechaty#4]
感谢大佬的出色成果，特别是对docker安装信息的多次更新！

请问docker的来源在哪，是开源的吗？如何跟踪更新？

registry.cn-chengdu.aliyuncs.com/tu1h/wechotd:alpine

**Comment by mikoshu** [comment]
docker 来自 https://github.com/Devo919/Gewechat?tab=readme-ov-file 然后自己重新优化 只有api是开源的 目前的镜像是群友更新的 你可以入群关注下
